# Generated by Django 4.1.7 on 2023-03-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_a', models.IntegerField(verbose_name='a')),
                ('num_b', models.IntegerField(verbose_name='b')),
            ],
            options={
                'db_table': 'sets',
            },
        ),
    ]
