# Generated by Django 4.1.7 on 2023-03-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_create_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='sum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
